import HomeClientsCard from "@/components/Home/HomeClientsCard";
import HomeGraph from "@/components/Home/HomeGraph";
import HomeLatestTest from "@/components/Home/HomeLatestTest";
import HomeTestsCard from "@/components/Home/HomeTestsCard";
import HomeTestsInProgressCard from "@/components/Home/HomeTestsInProgressCard";
import Head from "next/head";
export default function index() {
  return (
    <div>
      <Head>
        <title>Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-container">
        <h1 className="home_title">Stats</h1>
        <div className="cards-container">
          <HomeClientsCard />
          <HomeTestsCard />
          <HomeTestsInProgressCard />
          <HomeLatestTest />
          <HomeGraph />
        </div>
      </div>
    </div>
  );
}
