import Head from "next/head";
export default function index() {
  return (
    <div>
      <Head>
        <title>Case Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="clients">
        <h2>Clients</h2>
        <p>2150</p>
      </div>
    </div>
  );
}
